# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: localdrop

before:
  hooks:
    - go mod tidy

builds:
  - id: localdrop_unix
    binary: localdrop
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: localdrop_linux_32
    binary: localdrop
    goos:
      - linux
    goarch:
      - 386
      - arm
    goarm:
      - 7

  - id: localdrop_windows
    binary: localdrop
    goos:
      - windows
    goarch:
      - amd64
      - 386
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      localdrop_{{ .Os }}_{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
